// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MovieLibrary.Data;
using System;

namespace MovieLibrary.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20180424172705_addedMovieName")]
    partial class addedMovieName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieLibrary.Data.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActorName");

                    b.Property<string>("DirectorName");

                    b.Property<string>("Genre");

                    b.Property<string>("MovieName");

                    b.Property<DateTime>("ReleaseDate");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieLibrary.Data.Entities.MovieItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MovieId");

                    b.Property<int?>("MovieOrderId");

                    b.Property<decimal>("Price");

                    b.Property<int>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("MovieOrderId");

                    b.ToTable("MovieItems");
                });

            modelBuilder.Entity("MovieLibrary.Data.Entities.MovieOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("OrderDateTime");

                    b.Property<string>("OrderNumber");

                    b.HasKey("Id");

                    b.ToTable("MovieOrders");
                });

            modelBuilder.Entity("MovieLibrary.Data.Entities.MovieItem", b =>
                {
                    b.HasOne("MovieLibrary.Data.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.HasOne("MovieLibrary.Data.Entities.MovieOrder", "MovieOrder")
                        .WithMany("Items")
                        .HasForeignKey("MovieOrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
